//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Magic Survivors/Input/ViewInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ViewInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ViewInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ViewInputActions"",
    ""maps"": [
        {
            ""name"": ""KeyBoardAndMouse"",
            ""id"": ""aafe1209-ff19-4f11-9e0c-d9d3b6ac89ed"",
            ""actions"": [
                {
                    ""name"": ""ToggleMenu"",
                    ""type"": ""Button"",
                    ""id"": ""951c5ba8-a266-429d-8e7e-7cfa63e600fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f19d449c-bb31-4e3d-b22d-519bfcc10726"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyBoardAndMouse
        m_KeyBoardAndMouse = asset.FindActionMap("KeyBoardAndMouse", throwIfNotFound: true);
        m_KeyBoardAndMouse_ToggleMenu = m_KeyBoardAndMouse.FindAction("ToggleMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyBoardAndMouse
    private readonly InputActionMap m_KeyBoardAndMouse;
    private List<IKeyBoardAndMouseActions> m_KeyBoardAndMouseActionsCallbackInterfaces = new List<IKeyBoardAndMouseActions>();
    private readonly InputAction m_KeyBoardAndMouse_ToggleMenu;
    public struct KeyBoardAndMouseActions
    {
        private @ViewInputActions m_Wrapper;
        public KeyBoardAndMouseActions(@ViewInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleMenu => m_Wrapper.m_KeyBoardAndMouse_ToggleMenu;
        public InputActionMap Get() { return m_Wrapper.m_KeyBoardAndMouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyBoardAndMouseActions set) { return set.Get(); }
        public void AddCallbacks(IKeyBoardAndMouseActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Add(instance);
            @ToggleMenu.started += instance.OnToggleMenu;
            @ToggleMenu.performed += instance.OnToggleMenu;
            @ToggleMenu.canceled += instance.OnToggleMenu;
        }

        private void UnregisterCallbacks(IKeyBoardAndMouseActions instance)
        {
            @ToggleMenu.started -= instance.OnToggleMenu;
            @ToggleMenu.performed -= instance.OnToggleMenu;
            @ToggleMenu.canceled -= instance.OnToggleMenu;
        }

        public void RemoveCallbacks(IKeyBoardAndMouseActions instance)
        {
            if (m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyBoardAndMouseActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyBoardAndMouseActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyBoardAndMouseActions @KeyBoardAndMouse => new KeyBoardAndMouseActions(this);
    public interface IKeyBoardAndMouseActions
    {
        void OnToggleMenu(InputAction.CallbackContext context);
    }
}
